# Henry's newman runner

# TODO
# this should be triggered from kaltire-storelocator
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  
# FYI, there is a task from Azure marketplace called Newman, but its very buggy
# OR Azure Dev Ops has changed their pipeline framework to make this incompatible
# I'm leaning towards the latter
# Anways, just install 'newman' locally in ./node_modules/.bin
- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Install newman'

- script: |
    echo "Running newman scripts"
    # Download postman collection
    curl --location --request GET "https://api.getpostman.com/collections/9fb7efb0-0170-4cd8-ab11-e3d3a033e470" \
    --header "X-Api-Key: $(postman.api.key)" > 000.postman_collection.json
    # Download postman environment
    curl --location --request GET "https://api.getpostman.com/environments/ca6ee577-85df-44ab-b0e0-1eb35a92dd0f" \
    --header "X-Api-Key: $(postman.api.key)" > 000.postman_environment.json
    # Note to Henry ... if my demo fails, then don't download the files above ... just use the backup cache in github
    # Assume first collection and first environment file
    ./node_modules/.bin/newman run $(ls *collection.json | head -1) -e $(ls *environment.json | head -1) --reporters cli,junit
  displayName: 'Run newman'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'newman/*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true

