# Henry's newman runner

# TODO
# this should be triggered from kaltire-storelocator
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  
# FYI, there is a task from Azure marketplace called Newman, but its very buggy
# OR Azure Dev Ops has changed their pipeline framework to make this incompatible
# I'm leaning towards the latter
# Anways, just install 'newman' locally in ./node_modules/.bin
- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Install newman'

# Note to Henry ... if my demo fails due to the postman api limit, then don't download the files 
# just use the backup cache in github
# i.e. put an `exit` early in the script
- script: |
    # Remove collection and environment files
    rm *collection.json *environment.json
    # Download LATEST postman collection
    curl --location --request GET "https://api.getpostman.com/collections/9fb7efb0-0170-4cd8-ab11-e3d3a033e470" \
    --header "X-Api-Key: $(postman.api.key)" > 000.postman_collection.json
    # Download LATEST postman environment
    curl --location --request GET "https://api.getpostman.com/environments/ca6ee577-85df-44ab-b0e0-1eb35a92dd0f" \
    --header "X-Api-Key: $(postman.api.key)" > 000.postman_environment.json
    ls -l *.json
  displayName : 'Download latest postman collection and environment'

- script: |
    echo "Running newman scripts"
    # Assume first collection and first environment file
    ./node_modules/.bin/newman run $(ls *collection.json | head -1) -e $(ls *environment.json | head -1) --reporters cli,junit
  displayName: 'Run newman'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'newman/*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true

