# Henry's newman runner

# TODO
# this should be triggered from kaltire-storelocator
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  
# FYI, there is a task from Azure marketplace called Newman, but its very buggy
# OR Azure Dev Ops has changed their pipeline framework to make this incompatible
# I'm leaning towards the latter
# Anways, just install 'newman' locally in ./node_modules/.bin
- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Install newman'

- script: |
    echo "Running newman scripts"
    echo postman.api.key $(postman.api.key)
    # Note that the * glob below *could* be dangerous.  Assume only one collection and one environment file
    ./node_modules/.bin/newman run $(ls *collection.json) -e $(ls *environment.json) --reporters cli,junit
  displayName: 'Run newman'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'newman/*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true

