# Henry's newman runner

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  
# FYI, there is a task from Azure marketplace called Newman, but its very buggy
# OR Azure Dev Ops has changed their pipeline framework to make this incompatible
# I'm leaning towards the latter
# Anways, just install 'newman' locally in ./node_modules/.bin
- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Install newman'

- script: |
    echo "Running newman scripts"
    ./node_modules/.bin/newman run kaltire-storelocation.collection.json -e kaltire-prod-env.json
  displayName: 'Run newman'

